// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcYmD7h917IUb6HSJAATS6DgyVABajRKc',
    appId: '1:643025056879:android:6374850846321f3acbc99a',
    messagingSenderId: '643025056879',
    projectId: 'flash-chat-fae4d',
    storageBucket: 'flash-chat-fae4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDg0utBv-vBhQszbnXj6cM8lrhtpH7LY',
    appId: '1:643025056879:ios:1f5a3fdb96384012cbc99a',
    messagingSenderId: '643025056879',
    projectId: 'flash-chat-fae4d',
    storageBucket: 'flash-chat-fae4d.appspot.com',
    iosClientId: '643025056879-loqcf1ispv6db60p08otckb98k15iehf.apps.googleusercontent.com',
    iosBundleId: 'com.mohamednasser.app',
  );
}
